### ISSUE TITLE
Need to add CI of build_android back

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#6111]
Current PR often make the build of mobile failed. When I build for Android using the current develop branch, I met the following error:
- CMake warning
```
-- Configuring done
CMake Error at paddle/testing/CMakeLists.txt:10 (add_dependencies):
  The dependency target "paddle_memory" of target "paddle_gtest_main" does
  not exist.


```

- Make error
```
[ 84%] Building CXX object paddle/testing/CMakeFiles/paddle_gtest_main.dir/paddle_gtest_main.cc.o
In file included from /home/work/liuyiqun/PaddlePaddle/Paddle/paddle/platform/place.h:19:0,
                 from /home/work/liuyiqun/PaddlePaddle/Paddle/paddle/memory/memory.h:17,
                 from /home/work/liuyiqun/PaddlePaddle/Paddle/paddle/testing/paddle_gtest_main.cc:18:
/home/work/liuyiqun/PaddlePaddle/Paddle/paddle/platform/variant.h:17:28: fatal error: boost/config.hpp: No such file or directory
 #include <boost/config.hpp>
                            ^
compilation terminated.
make[2]: *** [paddle/testing/CMakeFiles/paddle_gtest_main.dir/paddle_gtest_main.cc.o] Error 1
make[1]: *** [paddle/testing/CMakeFiles/paddle_gtest_main.dir/all] Error 2
make: *** [all] Error 2
```

The error is caused by PR https://github.com/PaddlePaddle/Paddle/pull/5476. In fact, there is no need to build the source file `paddle_gtest_main.cc`.

We need to add CI of `build_android` back to make sure cross-compiling always successful.

**Comment by Yancey1989** [comment]
Will do this, and for another, what kind of trigger do you suggest? nightly or after merged?

**Comment by Xreki** [comment]
I think it should be triggered by each commit in PR. Every PR should ensure it does not fail the building of Android. 

Previously, I have added a `build_android` task in travis, and removed it for some reason. I am not sure where to add it, travis or teamcity? It seems the teamcity is slow now (~ 35 mins).

**Comment by Yancey1989** [comment]
I created a project on teamCity: https://paddleci.ngrok.io/viewType.html?buildTypeId=Paddle_BuildAndroid
