### PR TITLE
Fix CUDA 11.6 compilation error on fused_gemm_epilogue_op.cu

### PR DESCRIPTION
**Pull request by sneaxiy**
### PR types
Bug fixes

### PR changes
Others

### Describe
Fix CUDA 11.6 compilation error on fused_gemm_epilogue_op.cu caused by https://github.com/PaddlePaddle/Paddle/pull/45562 .

### CODE REVIEW

**Review by jiweibo — APPROVED** [review]
LGTM
