### ISSUE TITLE
failed to inference resnet50 example on GPU

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/Paddle#20786]
- PaddlePaddle version: 1.5.2
- CPU: Intel i7
- GPU: NVIDIA V100, CUDA 10, cuDNN 7.5.0, TensorRT 5.1 GA
- OS Platform: hub.baidubce.com/paddlepaddle/paddle:1.5.2-gpu-cuda10.0-cudnn7 (the docker image was downloaded from [here](https://www.paddlepaddle.org.cn/install/quick))
![paddle_install](https://user-images.githubusercontent.com/5894445/67454820-364ebf80-f65e-11e9-8285-5b9f22e0eabe.png)

```
$ nvidia-docker pull hub.baidubce.com/paddlepaddle/paddle:1.5.2-gpu-cuda10.0-cudnn7
```
- Python version: 2.7

**To Reproduce**
Follow the instructions provided by PaddlePaddle official website to download the model and run the code - `resnet50_infer.py`:
```
$ python resnet50_infer.py --model_file ./model/model --params_file ./model/params
```
All needed files can be found at [here](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_usage/deploy/inference/python_infer_cn.html)

**Describe current behavior**
It threw:
```
Traceback (most recent call last):
  File "./resnet50_infer.py", line 51, in <module>
    main()    
  File "./resnet50_infer.py", line 22, in main
    inputs = fake_input(args.batch_size)
  File "./resnet50_infer.py", line 39, in fake_input
    image = PaddleTensor(data)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. paddle.fluid.core_avx.PaddleTensor()
```

If replaced `config.disable_gpu()`  with `config.enable_use_gpu(100, 0)`, then it threw same error message either and NO GPU kernel was invoked (used nsight-system to check it).

**Code to reproduce the issue**
```python
import argparse                                                                                                                                                                                             
import numpy as np

from paddle.fluid.core import PaddleTensor
from paddle.fluid.core import AnalysisConfig
from paddle.fluid.core import create_paddle_predictor

def main():
    args = parse_args()

    # set AnalysisConfig
    config = AnalysisConfig(args.model_file, args.params_file)
    #config.disable_gpu()
    config.enable_use_gpu(100, 0)

    # create PaddlePredictor
    predictor = create_paddle_predictor(config)

    # set input
    inputs = fake_input(args.batch_size)

    # inference
    outputs = predictor.run(inputs)
    output_num = 512 

    # get output
    output = outputs[0]
    print(output.name)
    output_data = output.as_ndarray() #return numpy.ndarray
    assert list(output_data.shape) == [args.batch_size, output_num]
    for i in range(args.batch_size):
        print(np.argmax(output_data[i]))

def fake_input(batch_size):    
    shape = [batch_size, 3, 318, 318]
    data = np.random.randn(*shape).astype(np.float32)
    image = PaddleTensor(data)
    return [image]

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_file", type=str, default="model/model", help="model filename")
    parser.add_argument("--params_file", type=str, default="model/params", help="parameter filename")
    parser.add_argument("--batch_size", type=int, default=1, help="batch size")

    return parser.parse_args()

if __name__ == "__main__":
    main()
```
**Other info / logs**

**Comment by NHZlX** [comment]
使用的是cuda的lib么

**Comment by jeng1220** [comment]
What do you mean? The docker image includes CUDA libraries

**Comment by jeng1220** [comment]
@NHZlX ,
I changed PaddlePaddle version to `paddlepaddle-gpu 1.6.0.post107` via following instructions
```
$ python -m pip install paddlepaddle-gpu -i https://pypi.tuna.tsinghua.edu.cn/simple
```
then it can run `resnet50_infer.py` on GPU now.  I think the root-cause of problem is caused by the prebuilt PaddlePaddle in the docker image. We should update PaddlePaddle official website soon.


However, I encountered another problem after upgraded paddlepaddle-gpu to v1.6. When I tried to enable TensorRT as following
```
    config.enable_use_gpu(100, 0)
    config.enable_tensorrt_engine(precision=AnalysisConfig.Precision.kFloat32)
```
PaddlePaddle threw
```
Traceback (most recent call last):
  File "resnet50_infer.py", line 53, in <module>
    main()    
  File "resnet50_infer.py", line 15, in main
    config.enable_tensorrt_engine(precision=AnalysisConfig.Precision.kFloat32)
AttributeError: type object 'paddle.fluid.core_avx.Precision' has no attribute 'kFloat32'
```
Do you have any idea about this problem?

**Comment by OliverLPH** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/inference_api.cc#L309

it should be 'Float32' instead of 'kFloat32'

**Comment by jeng1220** [comment]
@OliverLPH,
I see, thanks for help. I found that there are 2 typos in official PaddlePaddle website ([link](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_usage/deploy/inference/python_infer_cn.html)):
![config](https://user-images.githubusercontent.com/5894445/67468602-6063aa00-f67d-11e9-9b86-53b1535b0fe2.png)

1. The correct parameter is `Float32` instead of `kFloat32`
2. The correct argument is `precision_mode` instead of `precision`

I think we better update the website too. Otherwise, it frustrates people.


However, after set up correct parameter and argument as following,
```
    config.enable_use_gpu(100, 0)
    config.enable_tensorrt_engine(precision_mode=AnalysisConfig.Precision.Float32)
```
I encountered new error
```
Traceback (most recent call last):
  File "resnet50_infer.py", line 55, in <module>
    main()    
  File "resnet50_infer.py", line 23, in main
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet: 0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ir::PassRegistry::Get(std::string const&) const
3   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
5   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::AnalysisPredictor::OptimizeInferenceProgram()
8   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
9   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
10  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
PaddleCheckError: Pass tensorrt_subgraph_pass has not been registered at [/paddle/paddle/fluid/framework/ir/pass.h:168]
```

**Comment by OliverLPH** [comment]
@jeng1220 
From your log, it looks like your paddle doesn't contain TensorRT subgraph.

I notice you instaledl paddle from docker? maybe you need try install from source code 
[installation guide](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/build_and_install_lib_cn.html)

And cmake should contain 'DTENSORRT_ROOT' 
```shell 
cmake ..  -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=ON \
      -DWITH_MKL=OFF \
      -DWITH_GPU=ON  \
      -DON_INFER=ON \
      -DTENSORRT_ROOT=${TensorRT_ROOT_DIR}
```

**Comment by jeng1220** [comment]
@OliverLPH, 
Thanks for help. I didn't find statement regarding `-DTENSORRT_ROOT=${TensorRT_ROOT_DIR}` in PaddlePaddle document. This is another thing which should be improved.

I tried to build from the source and encountered the bug #18985 so I have no choice to switch to `develop` branch (483d0512cea86609c4e3aa11ca1a8f05108b68e9) instead of v1.6 to build, then it threw:
```
fatal: no tag exactly matches '483d0512cea86609c4e3aa11ca1a8f05108b68e9'
python/CMakeFiles/paddle_python.dir/build.make:901: recipe for target 'python/build/.timestamp' faile
```
How do you handle this error?
This is my build options:
```
cmake .. -DPY_VERSION=3.6 \
                  -DWITH_GPU=ON \
                  -DWITH_TESTING=OFF \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DWITH_GPU=ON \
                  -DON_INFER=ON \
                  -DTENSORRT_ROOT=/usr  \
                  -DCUDA_ARCH_NAME=Auto
```

**Comment by OliverLPH** [comment]
@jeng1220 
I tried the following cmake options, but I haven't encounter your problem? I think you should enable DWITH_PYTHON=ON first. And if it still cannot work properly, I thought the problem might due to python environment, my suggestion is you can try to build Paddle by using Anaconda python environment.

```shell
cmake .. -DWITH_PYTHON=ON \
                  -DPY_VERSION=2.7 \
                  -DWITH_GPU=ON \
                  -DWITH_TESTING=OFF \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DWITH_GPU=ON \
                  -DON_INFER=ON \
                  -DTENSORRT_ROOT=/usr  \
                  -DCUDA_ARCH_NAME=Auto
```

**Comment by jeng1220** [comment]
@OliverLPH ,
In the default setting, `WITH_PYTHON` is ON, so I think it doesn't matter. 
https://github.com/PaddlePaddle/Paddle/blob/develop/CMakeLists.txt#L63
```
option(WITH_PYTHON      "Compile PaddlePaddle with python interpreter"  ON)
```
Anyway, I still tried it by following #18976 (looks like he succeeded and he used `-DWITH_PYTHON=ON `) .  However, I still encountered same error, so I tried to do what error message told - add a tag to 483d051 like:
```
$ git tag -a v1.6+ -m 'my v1.6+'
```
then I encountered new but similar error:
```
fatal: Not a valid object name 2>/dev/null
python/CMakeFiles/paddle_python.dir/build.make:901: recipe for target 'python/build/.timestamp' failed
```
The problem was caused by `python/build/.timestamp`, so I think it may has connection with Python version or CMake version, not sure...

- My Python version is 3.6.8
- My CMake version 3.12.1

**Comment by jeng1220** [comment]
@OliverLPH ,
After downgraded to Python 2.7, I still encountered same error:
```
fatal: no tag exactly matches '4bca147d3fe319911bf11c5bb0c0b6df5fb3e44d'
```
but building process didn't stop. It kept going and finally generated `paddlepaddle_gpu-0.0.0-cp27-cp27mu-linux_x86_64.whl`.

I think major issue is Python version because I didn't change other things. This means PaddlePaddle codebase has compatibility issue with Python 3.6+. We supposedly need someone to investigate this issue for future development.

**Comment by jeng1220** [comment]
@NHZlX ,

After solved above errors, I tried to run `resnet50_infer.py` on `develop` branch (3b31b74e205dcad70e4c09482dec1ed0eea83d60) again, then encountered segmentation fault. Note, If I only use `config.enable_use_gpu(100, 0)` without `config.enable_tensorrt_engine(...)`, it can run on GPU.

Log:
```
root@DevTech:/test/workspace/paddle/trt_sample/sample1# python ./resnet50_infer.py 
I1028 07:50:53.993088  6843 analysis_predictor.cc:88] Profiler is deactivated, and no profiling report will be generated.
I1028 07:50:53.996346  6843 op_compatible_info.cc:201] The default operator required version is missing. Please update the model version.
I1028 07:50:53.996357  6843 analysis_predictor.cc:847] MODEL VERSION: 0.0.0
I1028 07:50:53.996361  6843 analysis_predictor.cc:849] PREDICTOR VERSION: 0.0.0
W1028 07:50:53.996376  6843 analysis_predictor.cc:862]  - Version incompatible (1) batch_norm
W1028 07:50:53.996379  6843 analysis_predictor.cc:862]  - Version incompatible (1) conv2d
W1028 07:50:53.996381  6843 analysis_predictor.cc:862]  - Version incompatible (1) elementwise_add
W1028 07:50:53.996385  6843 analysis_predictor.cc:862]  - Version incompatible (1) feed
W1028 07:50:53.996390  6843 analysis_predictor.cc:862]  - Version incompatible (1) fetch
W1028 07:50:53.996395  6843 analysis_predictor.cc:862]  - Version incompatible (1) mul
W1028 07:50:53.996399  6843 analysis_predictor.cc:862]  - Version incompatible (1) pool2d
W1028 07:50:53.996403  6843 analysis_predictor.cc:862]  - Version incompatible (1) relu
W1028 07:50:53.996408  6843 analysis_predictor.cc:148] WARNING: Results may be DIFF! Please use the corresponding version of the model and prediction library, and do not use the develop branch.
I1028 07:50:53.996546  6843 analysis_predictor.cc:414] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
W1028 07:50:54.036341  6843 init.cc:205] *** Aborted at 1572249054 (unix time) try "date -d @1572249054" if you are using GNU date ***
W1028 07:50:54.036761  6843 init.cc:205] PC: @                0x0 (unknown)
W1028 07:50:54.036824  6843 init.cc:205] *** SIGSEGV (@0x50) received by PID 6843 (TID 0x7fbfb2b39740) from PID 80; stack trace: ***
W1028 07:50:54.037196  6843 init.cc:205]     @     0x7fbfb256df20 (unknown)
W1028 07:50:54.037485  6843 init.cc:205]     @     0x7fbfb292cac8 (unknown)
W1028 07:50:54.037772  6843 init.cc:205]     @     0x7fbfb29350bd (unknown)
W1028 07:50:54.038079  6843 init.cc:205]     @     0x7fbfb26962df _dl_catch_exception
W1028 07:50:54.038363  6843 init.cc:205]     @     0x7fbfb29347ca (unknown)
W1028 07:50:54.038719  6843 init.cc:205]     @     0x7fbfb26953ad (unknown)
W1028 07:50:54.039026  6843 init.cc:205]     @     0x7fbfb26962df _dl_catch_exception
W1028 07:50:54.039317  6843 init.cc:205]     @     0x7fbfb269636f _dl_catch_error
W1028 07:50:54.039665  6843 init.cc:205]     @     0x7fbfb26954d9 __libc_dlopen_mode
W1028 07:50:54.040019  6843 init.cc:205]     @     0x7fbfb2660075 (unknown)
W1028 07:50:54.040305  6843 init.cc:205]     @     0x7fbfb231f827 __pthread_once_slow
W1028 07:50:54.040643  6843 init.cc:205]     @     0x7fbfb266014f backtrace
W1028 07:50:54.042567  6843 init.cc:205]     @     0x7fbf709bb19d paddle::platform::GetTraceBackString<>()
W1028 07:50:54.043642  6843 init.cc:205]     @     0x7fbf709bb88e paddle::platform::EnforceNotMet::EnforceNotMet()
W1028 07:50:54.045305  6843 init.cc:205]     @     0x7fbf70c288dd paddle::framework::ir::PassRegistry::Get()
W1028 07:50:54.046772  6843 init.cc:205]     @     0x7fbf72d9842a paddle::inference::analysis::IRPassManager::CreatePasses()
W1028 07:50:54.049872  6843 init.cc:205]     @     0x7fbf72d9b1a4 paddle::inference::analysis::IRPassManager::IRPassManager()
W1028 07:50:54.051853  6843 init.cc:205]     @     0x7fbf72d925fd paddle::inference::analysis::IrAnalysisPass::RunImpl()
W1028 07:50:54.054944  6843 init.cc:205]     @     0x7fbf72d8b3b6 paddle::inference::analysis::Analyzer::RunAnalysis()
W1028 07:50:54.057199  6843 init.cc:205]     @     0x7fbf70c5ec93 paddle::AnalysisPredictor::OptimizeInferenceProgram()
W1028 07:50:54.060243  6843 init.cc:205]     @     0x7fbf70c5f30a paddle::AnalysisPredictor::PrepareProgram()
W1028 07:50:54.061949  6843 init.cc:205]     @     0x7fbf70c5f49f paddle::AnalysisPredictor::Init()
W1028 07:50:54.064626  6843 init.cc:205]     @     0x7fbf70c5f74b paddle::CreatePaddlePredictor<>()
W1028 07:50:54.067526  6843 init.cc:205]     @     0x7fbf70c601f0 paddle::CreatePaddlePredictor<>()
W1028 07:50:54.068477  6843 init.cc:205]     @     0x7fbf70b448e0 _ZZN8pybind1112cpp_function10initializeIRPFSt10unique_ptrIN6paddle15PaddlePredictorESt14default_deleteIS4_EERKNS3_14AnalysisConfigEES7_JSA_EJNS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESU_
W1028 07:50:54.069401  6843 init.cc:205]     @     0x7fbf709eee8f pybind11::cpp_function::dispatcher()
W1028 07:50:54.069490  6843 init.cc:205]     @     0x55fdc3b5229a PyEval_EvalFrameEx
W1028 07:50:54.069581  6843 init.cc:205]     @     0x55fdc3b568cd PyEval_EvalFrameEx
W1028 07:50:54.069667  6843 init.cc:205]     @     0x55fdc3b4fb0a PyEval_EvalCodeEx
W1028 07:50:54.069752  6843 init.cc:205]     @     0x55fdc3b4f429 PyEval_EvalCode
W1028 07:50:54.069840  6843 init.cc:205]     @     0x55fdc3b7f4cf (unknown)
W1028 07:50:54.069908  6843 init.cc:205]     @     0x55fdc3b7a442 PyRun_FileExFlags
Segmentation fault (core dumped)
```

**Comment by jeng1220** [comment]
@NHZlX ,
After investigated `tensorrt.cmake`, I finally could run `resnet50_infer.py` with TensorRT. I have submitted PR #20858. Please help to review and merge.

**Comment by jeng1220** [comment]
Because  #20858 was merged, close this issue
