### PR TITLE
Patch mkldnn for build on gcc 4.8.2

### LINKED ISSUE #10584: mkldnn compiler error in gcc48
When gcc version is 4.8.3:
https://paddleci.ngrok.io/viewLog.html?buildId=35590&buildTypeId=Manylinux1_Cuda80cudnn5cp27cp27mu&tab=buildLog&_focus=3589
- a lot of `-Werror=unused-result`
```
In file included from /home/luotao02/Paddle/build/third_party/mkldnn/src/extern_mkldnn/src/cpu/cpu_barrier.hpp:22:0,
                 from /home/luotao02/Paddle/build/third_party/mkldnn/src/extern_mkldnn/src/cpu/cpu_barrier.cpp:19:
/home/luotao02/Paddle/build/third_party/mkldnn/src/extern_mkldnn/src/cpu/jit_generator.hpp: In member function ‘void mkldnn::impl::cpu::jit_generator::dump_code(const uint8*) const’:
/home/luotao02/Paddle/build/third_party/mkldnn/src/extern_mkldnn/src/cpu/jit_generator.hpp:719:47: error: ignoring return value of ‘size_t fwrite(const void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Werror=unused-result]
                 fwrite(code, getSize(), 1, fp);
                                               ^
```
- after fix `-Werror=unused-result`, there is `-Werror=missing-field-initializers`
```
In file included from /home/luotao02/Paddle/paddle/fluid/platform/device_context.h:26:0,
                 from /home/luotao02/Paddle/paddle/fluid/platform/device_context.cc:11:
/home/luotao02/Paddle/build/third_party/install/mkldnn/include/mkldnn.hpp: In function ‘mkldnn::memory::desc mkldnn::zero_md()’:
/home/luotao02/Paddle/build/third_party/install/mkldnn/include/mkldnn.hpp:796:31: error: missing initializer for member ‘mkldnn_memory_desc_t::primitive_kind’ [-Werror=missing-field-initializers]
     mkldnn_memory_desc_t zero{};
                               ^
/home/luotao02/Paddle/build/third_party/install/mkldnn/include/mkldnn.hpp:796:31: error: missing initializer for member ‘mkldnn_memory_desc_t::ndims’ [-Werror=missing-field-initializers]
/home/luotao02/Paddle/build/third_party/install/mkldnn/include/mkldnn.hpp:796:31: error: missing initializer for member ‘mkldnn_memory_desc_t::dims’ [-Werror=missing-field-initializers]
/home/luotao02/Paddle/build/third_party/install/mkldnn/include/mkldnn.hpp:796:31: error: missing initializer for member ‘mkldnn_memory_desc_t::data_type’ [-Werror=missing-field-initializers]
/home/luotao02/Paddle/build/third_party/install/mkldnn/include/mkldnn.hpp:796:31: error: missing initializer for member ‘mkldnn_memory_desc_t::format’ [-Werror=missing-field-initializers]
/home/luotao02/Paddle/build/third_party/install/mkldnn/include/mkldnn.hpp:796:31: error: missing initializer for member ‘mkldnn_memory_desc_t::layout_desc’ [-Werror=missing-field-initializers]
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/platform/CMakeFiles/device_context.dir/device_context.cc.o] Error 1
make[1]: *** [paddle/fluid/platform/CMakeFiles/device_context.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX static library libpaddle_test_util.a
[ 20%] Built target paddle_test_util
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by typhoonzero**
fix #10584

### CODE REVIEW

File: cmake/external/mkldnn.cmake [hunk 1]
```diff
@@ -56,6 +56,7 @@ ExternalProject_Add(
     GIT_TAG             "v0.14"
     PREFIX              ${MKLDNN_SOURCES_DIR}
     UPDATE_COMMAND      ""
+    PATCH_COMMAND       ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_SOURCE_DIR}/patches/mkldnn.hpp ${MKLDNN_SOURCES_DIR}/src/extern_mkldnn/include/mkldnn.hpp
```
[the remark this answers is not in the document]
Comment (typhoonzero) [reply cmake/external/mkldnn.cmake]: Done.
