### PR TITLE
fix compiler error, use len20 dataset for bert

### PR DESCRIPTION
**Pull request by luotao1**
- fix compiler error, which is caused by #15540 and #15485
```
/home/luotao/Paddle/paddle/fluid/inference/tests/api/analyzer_rnn1_tester.cc:23:17: error: ‘contrib’ is not a namespace-name
 using namespace contrib;    // NOLINT
                 ^
/home/luotao/Paddle/paddle/fluid/inference/tests/api/analyzer_rnn1_tester.cc:23:24: error: expected namespace-name before ‘;’ token
 using namespace contrib;    // NOLINT
                        ^
make[2]: *** [paddle/fluid/inference/tests/api/CMakeFiles/test_analyzer_rnn1.dir/build.make:63: paddle/fluid/inference/tests/api/CMakeFiles/test_analyzer_rnn1.dir/analyzer_rnn1_tester.cc.o] Error 1
```
- use `max_len=20` and `SERIAL run` for analyzer_bert_test

### CODE REVIEW

**Review by Superjomn — APPROVED** [review]
LGTM
