### PR TITLE
Add INT8 calibration support in Paddle package

### PR DESCRIPTION
**Pull request by hshen14**
This PR is to add INT8 calibration utility into Paddle python package by default.

test=develop

### CODE REVIEW

**Comment by hshen14** [comment]
@luotao1 There are some unexpected errors:
[04:37:03]W:	 [Step 1/1] /home/teamcity/work/37d0fbdf11d96284/paddle/fluid/inference/tests/api/analyzer_bert_tester.cc:21:15: error: no member named 'contrib' in namespace 'paddle'
[04:37:03]W:	 [Step 1/1] using paddle::contrib::AnalysisConfig;
[04:37:03]W:	 [Step 1/1]       ~~~~~~~~^
[04:37:03]W:	 [Step 1/1] /home/teamcity/work/37d0fbdf11d96284/paddle/fluid/inference/tests/api/analyzer_bert_tester.cc:161:16: error: use of undeclared identifier 'contrib'
[04:37:03]W:	 [Step 1/1] void SetConfig(contrib::AnalysisConfig *config) {
[04:37:03]W:	 [Step 1/1]                ^
[04:37:03]W:	 [Step 1/1] /home/teamcity/work/37d0fbdf11d96284/paddle/fluid/inference/tests/api/analyzer_bert_tester.cc:166:3: error: use of undeclared identifier 'contrib'
[04:37:03]W:	 [Step 1/1]   contrib::AnalysisConfig config;
[04:37:03]W:	 [Step 1/1]   ^
[04:37:03] :	 [Step 1/1] [ 98%] Linking CXX executable test_inference_word2vec
[04:37:03] :	 [Step 1/1] [ 98%] Built target test_inference_recognize_digits_conv
[04:37:04] :	 [Step 1/1] Scanning dependencies of target test_analyzer_lac
[04:37:04] :	 [Step 1/1] [ 98%] Building CXX object paddle/fluid/inference/tests/api/CMakeFiles/test_analyzer_lac.dir/analyzer_lac_tester.cc.o
[04:37:04] :	 [Step 1/1] [ 98%] Built target test_inference_nlp
[04:37:04]W:	 [Step 1/1] 3 errors generated.

http://ci.paddlepaddle.org/viewLog.html?buildId=54529&buildTypeId=PaddleMac_MacPrCi&tab=buildLog

**Comment by luotao1** [comment]
fixed by #15570, please wait for it at first.

**Comment by hshen14** [comment]
> fixed by #15570, please wait for it at first.

OK. Please let me know the proper time to rerun test.

**Comment by luotao1** [comment]
Please test this PR at first. After merging this PR, the command is still error:
```
python python/paddle/fluid/contrib/tests/test_calibration.py
```
- update `python/paddle/fluid/contrib/__init__.py`
- use `import paddle.int8_inference.utility as int8_utility`
https://github.com/PaddlePaddle/Paddle/blob/655179089f79718b85ebb3fd9f9ea196773ea2f6/python/paddle/fluid/contrib/tests/test_calibration.py#L30

Besides, CI is normal now.

**Comment by hshen14** [comment]
> Please test this PR at first. After merging this PR, the command is still error:
> 
> ```
> python python/paddle/fluid/contrib/tests/test_calibration.py
> ```
> * update `python/paddle/fluid/contrib/__init__.py`
> * use `import paddle.int8_inference.utility as int8_utility`
>   
>     
>       
>         [Paddle/python/paddle/fluid/contrib/tests/test_calibration.py](https://github.com/PaddlePaddle/Paddle/blob/655179089f79718b85ebb3fd9f9ea196773ea2f6/python/paddle/fluid/contrib/tests/test_calibration.py#L30)
>       
>       
>            Line 30
>         in
>         [6551790](/PaddlePaddle/Paddle/commit/655179089f79718b85ebb3fd9f9ea196773ea2f6)
>       
>       
>       
>       
>   
>           
>             
>              import int8_inference.utility as int8_utility
> 
> Besides, CI is normal now.

It depends on https://github.com/PaddlePaddle/Paddle/pull/15560. Will try locally first

**Comment by luotao1** [comment]
> It depends on #15560

Why this PR depends on #15560? After package into the whl, `python test_calibration.py` could run.

**Comment by hshen14** [comment]
> > It depends on #15560
> 
> Why this PR depends on #15560? After package into the whl, `python test_calibration.py` could run.

I mean 15560 is to make sure functionality first and then enhance the packing in this PR.

**Comment by luotao1** [comment]
Since `test_calibration.py` is not packaged into whl, you can update this PR at first.

**Comment by hshen14** [comment]
> Since `test_calibration.py` is not packaged into whl, you can update this PR at first.

Could you please help confirm whether the below commands are good to reproduce? Thanks.

cmake -DCMAKE_INSTALL_PREFIX=./tmp DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=OFF -DWITH_PROFILER=ON -DWITH_MKL=ON  ..
make -j && make install
pip uninstall paddlepaddle -y && pip install --user tmp/opt/paddle/share/wheels/paddlepaddle-0.0.0-cp27-cp27mu-linux_x86_64.whl 

python python/paddle/fluid/contrib/tests/test_calibration.py

**Review by luotao1 — DISMISSED** [review]
LGTM

**Comment by luotao1** [comment]
```
[09:56:09][Step 1/1] + sed -i '/.*ComposeNotAligned.*/d' new.spec
[09:56:09][Step 1/1] + python /paddle/tools/diff_api.py /paddle/paddle/fluid/API.spec new.spec
[09:56:09][Step 1/1] API Difference is: 
[09:56:09][Step 1/1] + paddle.fluid.contrib.Calibrator.__init__ ArgSpec(args=['self'], varargs='args', keywords='kwargs', defaults=None)
[09:56:09][Step 1/1] + paddle.fluid.contrib.Calibrator.sample_data ArgSpec(args=['self'], varargs=None, keywords=None, defaults=None)
[09:56:09][Step 1/1] + paddle.fluid.contrib.Calibrator.save_int8_model ArgSpec(args=['self'], varargs=None, keywords=None, defaults=None)
```
http://ci.paddlepaddle.org/viewLog.html?buildId=54734&buildTypeId=Paddle_PrCi&tab=buildLog&_focus=16256
please update API.spec

**Comment by hshen14** [comment]
> ```
> [09:56:09][Step 1/1] + sed -i '/.*ComposeNotAligned.*/d' new.spec
> [09:56:09][Step 1/1] + python /paddle/tools/diff_api.py /paddle/paddle/fluid/API.spec new.spec
> [09:56:09][Step 1/1] API Difference is: 
> [09:56:09][Step 1/1] + paddle.fluid.contrib.Calibrator.__init__ ArgSpec(args=['self'], varargs='args', keywords='kwargs', defaults=None)
> [09:56:09][Step 1/1] + paddle.fluid.contrib.Calibrator.sample_data ArgSpec(args=['self'], varargs=None, keywords=None, defaults=None)
> [09:56:09][Step 1/1] + paddle.fluid.contrib.Calibrator.save_int8_model ArgSpec(args=['self'], varargs=None, keywords=None, defaults=None)
> ```
> http://ci.paddlepaddle.org/viewLog.html?buildId=54734&buildTypeId=Paddle_PrCi&tab=buildLog&_focus=16256
> please update API.spec

Done

**Comment by hshen14** [comment]
@panyx0718 Could you please review and approve the API.spec change? @luotao1 

[12:58:29]W:	 [Step 1/1] + APPROVALS=FALSE
[12:58:29]W:	 [Step 1/1] + echo 'current pr 15569 got approvals: FALSE'
[12:58:29]W:	 [Step 1/1] + '[' FALSE == FALSE ']'
[12:58:29]W:	 [Step 1/1] + echo 'You must have panyx0718 approval for the api change! paddle/fluid/API.spec'
[12:58:29]W:	 [Step 1/1] + exit 1
[12:58:29] :	 [Step 1/1] current pr 15569 got approvals: FALSE
[12:58:29] :	 [Step 1/1] You must have panyx0718 approval for the api change! paddle/fluid/API.spec

**Review by luotao1 — APPROVED** [review]

**Review by wzzju — APPROVED** [review]
LGTM.

**Review by panyx0718 — APPROVED** [review]
