### ISSUE TITLE
Regression: Fails to compile for ARM64 (Jetson) with latest develop branch

### ISSUE THREAD

**Issue by chancezeus** [PaddlePaddle/Paddle#35065]
When compiling for ARM using the following steps:
```bash
$ CUDA_HOME=/usr/local/cuda-10.2 PATH=$PATH:$CUDA_HOME/bin CUDACXX=$CUDA_HOME/bin/nvcc cmake .. -DWITH_CONTRIB=OFF -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_INFERENCE_API_TEST=OFF -DON_INFER=ON -DWITH_PYTHON=OFF -DWITH_NV_JETSON=ON -DWITH_NCCL=OFF -DCUDA_ARCH_NAME=All -DWITH_TENSORRT=ON -DWITH_ARM=ON -DWITH_GPU=ON -DWITH_XBYAK=OFF

$ make TARGET=ARMV8 -j8
```

It fails with the following error:
```
In file included from /source/paddle/fluid/memory/allocation/spin_lock.h:17:0,
                 from /source/paddle/fluid/memory/allocation/auto_growth_best_fit_allocator.h:24,
                 from /source/paddle/fluid/memory/allocation/auto_growth_best_fit_allocator.cc:15:
/source/paddle/fluid/memory/allocation/spin_lock_c.h: In member function ‘virtual paddle::memory::allocation::Allocation* paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(size_t)’:
/source/paddle/fluid/memory/allocation/spin_lock_c.h:113:45: error: impossible constraint in ‘asm’
                            : "memory", "cc");
                                             ^
paddle/fluid/memory/allocation/CMakeFiles/auto_growth_best_fit_allocator.dir/build.make:75: recipe for target 'paddle/fluid/memory/allocation/CMakeFiles/auto_growth_best_fit_allocator.dir/auto_growth_best_fit_allocator.cc.o' failed
make[2]: *** [paddle/fluid/memory/allocation/CMakeFiles/auto_growth_best_fit_allocator.dir/auto_growth_best_fit_allocator.cc.o] Error 1
CMakeFiles/Makefile2:3914: recipe for target 'paddle/fluid/memory/allocation/CMakeFiles/auto_growth_best_fit_allocator.dir/all' failed
make[1]: *** [paddle/fluid/memory/allocation/CMakeFiles/auto_growth_best_fit_allocator.dir/all] Error 2
```

Looking at the file, it seems that this was introduced in PR #34910 which got merged, however the asm code used in that file seems to be x86 only (no expert on arm asm, but I did look at the __asm__ docs and it seems that the "=a" condition is not available on arm (and perhaps other things too)), meaning that it breaks ARM (and thus Jetson) support.

Since I plan on compiling/running against TRT8 I need the develop branch (because that branch contains the required fixes for TRT8 which are lacking in 2.1 release branch), so I hope that someone can fix the relevant file so it works on ARM as well.

**Comment by jesen8** [comment]
meet the same problem

**Comment by jesen8** [comment]
1）PaddlePaddle版本：CommitID 56c5e2107611690fb36513ed70c9c5c17d7f5c08
    2）CPU：jetson nano
    3）GPU：
    4）os version：gcc 8.2.0

**Comment by chenjiaoAngel** [comment]
这个问题已有同学在修复，预计本周内可修复

**Comment by jesen8** [comment]
@chenjiaoAngel  您好，使用最新的develop分支编译，依然还有这个错误
