### ISSUE TITLE
dist.all_gather() can not work on window 10& paddlepaddle-gpu==2.2.1

### ISSUE THREAD

**Issue by songxujay** [PaddlePaddle/Paddle#37854]
>>>import paddle.distributed as dist
>>> t=[]
>>> out=[]
>>> dist.all_gather(a, out)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\files\anaconda3\envs\paddle\lib\site-packages\paddle\distributed\collective.py", line 636, in all_gather
    out = _C_ops.c_allgather(tensor, 'use_calc_stream', use_calc_stream,
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'c_allgather'

**Comment by wangxicoding** [comment]
Sorry, c_allgather is only supported in linux.

**Comment by songxujay** [comment]
Thanks for your reply. BTW, dist.all_gather() can just be used on Linux? How about windows?

**Comment by wangxicoding** [comment]
yes, dist.all_gather() is impl by NCCL which only supports Linux, doesn't support Windows.

**Comment by wenhwu** [comment]
@wangxicoding ，请问在win10下有没有`dist.all_gather()`的替代方案呢？

谢谢
