### ISSUE TITLE
Build error on LayerNorm fuse pass

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#30955]
If we use `paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7` or GCC4.8.2, there is error:
```
In file included from /home/luotao/Paddle/paddle/fluid/platform/enforce.h:65:0,
                 from /home/luotao/Paddle/paddle/fluid/framework/attribute.h:28,
                 from /home/luotao/Paddle/paddle/fluid/framework/op_desc.h:22,
                 from /home/luotao/Paddle/paddle/fluid/framework/block_desc.h:24,
                 from /home/luotao/Paddle/paddle/fluid/framework/ir/layer_norm_fuse_pass_tester.cc:19:
/home/luotao/Paddle/paddle/fluid/framework/block_desc.h: In constructor ‘paddle::framework::ir::{anonymous}::LayerNormFuseTest::LayerNormFuseTest()’:
/home/luotao/Paddle/paddle/fluid/framework/block_desc.h:122:27: error: ‘paddle::framework::BlockDesc::BlockDesc(const paddle::framework::BlockDesc&)’ is private
   DISABLE_COPY_AND_ASSIGN(BlockDesc);
                           ^
/home/luotao/Paddle/paddle/fluid/platform/macros.h:22:3: note: in definition of macro ‘DISABLE_COPY_AND_ASSIGN’
   classname(const classname&) = delete;            \
   ^
/home/luotao/Paddle/paddle/fluid/framework/ir/layer_norm_fuse_pass_tester.cc:47:37: error: within this context
         m_block_desc{m_prog.Block(0)} {
                                     ^
/home/luotao/Paddle/paddle/fluid/framework/ir/layer_norm_fuse_pass_tester.cc:47:37: error: use of deleted function ‘paddle::framework::BlockDesc::BlockDesc(const paddle::framework::BlockDesc&)’
In file included from /home/luotao/Paddle/paddle/fluid/platform/enforce.h:65:0,
                 from /home/luotao/Paddle/paddle/fluid/framework/attribute.h:28,
                 from /home/luotao/Paddle/paddle/fluid/framework/op_desc.h:22,
                 from /home/luotao/Paddle/paddle/fluid/framework/block_desc.h:24,
                 from /home/luotao/Paddle/paddle/fluid/framework/ir/layer_norm_fuse_pass_tester.cc:19:
/home/luotao/Paddle/paddle/fluid/framework/block_desc.h:122:27: error: declared here
   DISABLE_COPY_AND_ASSIGN(BlockDesc);
                           ^
/home/luotao/Paddle/paddle/fluid/platform/macros.h:22:3: note: in definition of macro ‘DISABLE_COPY_AND_ASSIGN’
   classname(const classname&) = delete;            \
   ^
/home/luotao/Paddle/paddle/fluid/framework/ir/layer_norm_fuse_pass_tester.cc:47:37: error: a temporary bound to ‘paddle::framework::ir::{anonymous}::LayerNormFuseTest::m_block_desc’ only persists until the constructor exits [-Werror=extra]
         m_block_desc{m_prog.Block(0)} {
                                     ^
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/framework/ir/CMakeFiles/test_layer_norm_fuse_pass_cc.dir/build.make:63: paddle/fluid/framework/ir/CMakeFiles/test_layer_norm_fuse_pass_cc.dir/layer_norm_fuse_pass_tester.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:21707: paddle/fluid/framework/ir/CMakeFiles/test_layer_norm_fuse_pass_cc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
It is caused by #30891
@arogowie-intel Could you please fix it ASAP? Thanks very much!

**Comment by arogowie-intel** [comment]
@luotao1 The fix is implemented in PR [30962](https://github.com/PaddlePaddle/Paddle/pull/30962)
